### ISSUE TITLE
Permanent ID auto-assignment causes resource conflicts in Rubydora

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#156]
One example:

```
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:48:in `return!'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/request.rb:495:in `process_result'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
/home/hydra/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rest-client-1.7.2/lib/restclient/resource.rb:76:in `put'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:370:in `modify_datastream'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/repository.rb:19:in `modify_datastream'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/datastream.rb:312:in `block in save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/datastream.rb:307:in `save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/datastream.rb:51:in `save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/digital_object.rb:285:in `block in save_datastreams'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/digital_object.rb:284:in `each'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/digital_object.rb:284:in `save_datastreams'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/rubydora-1.8.1/lib/rubydora/digital_object.rb:207:in `save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/persistence.rb:167:in `persist'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/callbacks.rb:236:in `block in persist'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:113:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:287:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:287:in `block in halting_and_conditional'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/callbacks.rb:236:in `persist'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/persistence.rb:157:in `update_record'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/callbacks.rb:244:in `block in update_record'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/callbacks.rb:244:in `update_record'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/persistence.rb:41:in `save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/validations.rb:50:in `save'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/persistence.rb:45:in `save!'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/active-fedora-7.1.2/lib/active_fedora/validations.rb:56:in `save!'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/ddr-models-1.11.4/lib/ddr/managers/permanent_id_manager.rb:76:in `assign!'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/ddr-models-1.11.4/lib/ddr/managers/permanent_id_manager.rb:37:in `block in assign'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `block in instrument'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/activesupport-4.1.9/lib/active_support/notifications.rb:159:in `instrument'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/ddr-models-1.11.4/lib/ddr/managers/permanent_id_manager.rb:31:in `assign'
/home/hydra/.rvm/gems/ruby-2.1.3@dul-hydra/gems/ddr-models-1.11.4/lib/ddr/managers/permanent_id_manager.rb:53:in `perform'
```

**Comment by dchandekstark** [comment]
Sketch of possible solution:

```ruby
# pseudocode
class Ddr::Managers::PermanentIdManager
  def self.assign(pid)
    if ActiveFedora::Base.exists?("id:\"#{pid}\" AND -permanent_id_ssi:*")
      # mint
      obj = ActiveFedora::Base.find(pid)
      obj.permanent_id = ...
      obj.permanent_url = ...
      obj.save!
    elsif ActiveFedora::Base.exists?(pid)
      # obj having pid already has permanent id
    else
      # obj having pid does not exist
    end
  end
end
```

**Comment by dchandekstark** [comment]
The problem has been temporarily dodged by disabling auto-assignment of permanent ids via the after_create callback.
