### ISSUE TITLE
multires_image_file_paths returns SolrDocument not found error

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-models#578]
@coblej 

The identifier used below is for an item (ingested locally) that is the parent of one or more components that have a multires_image_file_path.

```
> sdoc = SolrDocument.find('b0/af/d0/ea/b0afd0ea-f3ce-4682-a283-cf972fd87621')
> sdoc.multires_image_file_paths
Ddr::Models::SolrDocument::NotFound: SolrDocument not found for "info:fedora/changeme:1014".
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/ddr-models-3.0.0.beta.11/lib/ddr/models/solr_document.rb:17:in `find'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/ddr-models-3.0.0.beta.11/lib/ddr/models/solr_document.rb:264:in `block in struct_map_docs'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/ddr-models-3.0.0.beta.11/lib/ddr/models/solr_document.rb:264:in `map'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/ddr-models-3.0.0.beta.11/lib/ddr/models/solr_document.rb:264:in `struct_map_docs'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/ddr-models-3.0.0.beta.11/lib/ddr/models/solr_document.rb:221:in `multires_image_file_paths'
	from (irb):22
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/railties-4.1.14.1/lib/rails/commands/console.rb:90:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/railties-4.1.14.1/lib/rails/commands/console.rb:9:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/vagrant/.rvm/gems/ruby-2.1.5@ddr-public-f4/gems/railties-4.1.14.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by coblej** [comment]
Data issue, not code issue (not least not ddr-models code issue) -- cf. https://github.com/duke-libraries/dul-hydra/issues/1632
